# Generated by Django 5.0.6 on 2024-06-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_roominfo_hotel_price_roominfo_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='room',
            field=models.ImageField(default=None, upload_to='hotels/'),
        ),
    ]
