# Generated by Django 5.0.6 on 2024-06-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bookinginfo_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='person',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='hotel_price',
            field=models.IntegerField(default=1800),
        ),
        migrations.AlterField(
            model_name='roominfo',
            name='room_spec',
            field=models.CharField(max_length=600),
        ),
    ]
