# Generated by Django 5.0.6 on 2024-06-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_bookinginfo_person_alter_roominfo_hotel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='contactno',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='person',
            field=models.IntegerField(),
        ),
    ]
