# Generated by Django 5.0.6 on 2024-06-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_bookinginfo_contactno_alter_bookinginfo_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
