# Generated by Django 5.0.6 on 2024-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userdata_fname_userdata_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
